services:
  mysql:
    image: mysql:8.0
    container_name: hotel_reservas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "espe123"
      MYSQL_DATABASE: hotel_reservas
    ports:
      - "3306:3306"
    volumes:
      - ./hotel_reservas.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
